version: '2'

services:
  sentinel:
    build: 
      context: .
      args: 
        - REQUIREPASS=12345678
        - QUORUM=1
    environment:
      - REQUIREPASS=12345678
      - QUORUM=1
      - CLIENTPORT=26479
      - MASTERPORT=6479
      - MASTERHOST=localhost
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    network_mode: "host"
    image: crossz/sentinel-redis-distributed

